G77 = g77 -ggdb 

OBJECTS = america.o \
	contor.o \
	hardspheres.o  \
	mountain2.o \
	piecefit.o \
	bratu3Db.o \
	ellipsoid.o \
	kissing2.o \
	packccmn.o \
	simfock2.o \
	cache.o \
	genpack-cc-mina.o \
	kissing.o \
	packccmn-feas.o \
	simfock.o \
	condor.o \
	genpack-csq-mina.o \
	location.o \
	packcrmn-feas.o \
	contor2.o \
	hardcube.o \
	mountain1.o \
	pedazos4.o

all: $(OBJECTS)

america.o: america.f
	$(G77) -c america.f -o america.o
contor.o: contor.f
	$(G77) -c contor.f -o contor.o
hardspheres.o: hardspheres.f
	$(G77) -c hardspheres.f -o hardspheres.o
mountain2.o: mountain2.f
	$(G77) -c mountain2.f -o mountain2.o
piecefit.o: piecefit.f
	$(G77) -c piecefit.f -o piecefit.o
bratu3Db.o: bratu3Db.f
	$(G77) -c bratu3Db.f -o bratu3Db.o
ellipsoid.o: ellipsoid.f
	$(G77) -c ellipsoid.f -o ellipsoid.o
kissing2.o: kissing2.f
	$(G77) -c kissing2.f -o kissing2.o
packccmn.o: packccmn.f
	$(G77) -c packccmn.f -o packccmn.o
simfock2.o: simfock2.f
	$(G77) -c simfock2.f -o simfock2.o
cache.o: cache.f
	$(G77) -c cache.f -o cache.o
genpack-cc-mina.o: genpack-cc-mina.f
	$(G77) -c genpack-cc-mina.f -o genpack-cc-mina.o
kissing.o: kissing.f
	$(G77) -c kissing.f -o kissing.o
packccmn-feas.o: packccmn-feas.f
	$(G77) -c packccmn-feas.f -o packccmn-feas.o
simfock.o: simfock.f
	$(G77) -c simfock.f -o simfock.o
condor.o: condor.f
	$(G77) -c condor.f -o condor.o
genpack-csq-mina.o: genpack-csq-mina.f
	$(G77) -c genpack-csq-mina.f -o genpack-csq-mina.o
location.o: location.f
	$(G77) -c location.f -o location.o
packcrmn-feas.o: packcrmn-feas.f
	$(G77) -c packcrmn-feas.f -o packcrmn-feas.o
contor2.o: contor2.f
	$(G77) -c contor2.f -o contor2.o
hardcube.o: hardcube.f
	$(G77) -c hardcube.f -o hardcube.o
mountain1.o: mountain1.f
	$(G77) -c mountain1.f -o mountain1.o
pedazos4.o: pedazos4.f
	$(G77) -c pedazos4.f -o pedazos4.o
